### DISCUSSION TITLE
Running this behind HAProxy does not load the CSS?

### DISCUSSION THREAD

**Discussion by nosebeggar** [gogs/gogs#7360] [Q&A]
Hi all,

I realize there is an FAQ section, but that only covers apache, lighttpd and nginx.
I'm running this behind a haproxy, and it runs halfway. The requests are somehow tunneled through but some timeout, more precisely it looks like the CSS is not loading.

I'm running this as a docker container, I've set up the link as https://MYDOMAIN.IO:3000 and my haproxy config looks like this:

```
backend gogs
    fullconn 1000
    mode http
    timeout http-keep-alive 5000
    server local1 127.0.0.1:3001 check maxconn 100
    http-request set-header X-Forwarded-For MYDOMAIN.IO
    http-request set-header X-Forwarded-Port "3000"
    http-request set-header X-Forwarded-Proto "http"
```

This is my docker-compose file:
```
version: '2'

services:
  gogs:
    container_name: gogs
    restart: always
    image: gogs/gogs:latest
    ports:
        - "3022:22"
        - "3001:3000"
    volumes:
        - "./data:/data/"
        - "./repo:/data/git/gogs-repositories"
    environment:
        - "RUN_CROND=true"
volumes:
    gogs-data:
        driver: local
```

I am not sure how to fix this.
