### DISCUSSION TITLE
Gogs uses wrong user

### DISCUSSION THREAD

**Discussion by AlexBrightwater** [gogs/gogs#7675] [Q&A] [answered]
I didn't set a specific user for gogs to use in my docker-compose.yml. And I didn't notice, that gogs started to use the user 1000 which is a account of a human user on the server. 
I tried to add `user: 33:33` to the app service but that made the container unresponsive and not starting properly. 
If anyone uses how to change the user of gogs after initial setup, please explain how to do so. :) 

My docker-compose.yml:
```
version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: gogs
      POSTGRES_PASSWORD: redacted
      POSTGRES_DB: gogs
    volumes:
      - /mnt/sda1/volumes/gogs_postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - gogs_net

  app:
    image: gogs/gogs
    user: "33:33" # This didn't work at all (I though that www-data would be a fitting user)
    depends_on:
      - db
    ports: 
      - 2222:22
    volumes:
      - /mnt/fuse/volumes/gogs_data:/data
    restart: always
    environment:
      DB_TYPE: postgres
      DB_HOST: db:5432
      DB_NAME: gogs
      DB_USER: gogs
      DB_PASSWD: redacted
    links:
      - db:db
    networks:
      - reverse-proxy-net
      - gogs_net

networks:
  reverse-proxy-net:
    external: true
  gogs_net:
    driver: bridge
```
