### ISSUE TITLE
Prevent page jumping 

### ISSUE THREAD

**Issue by blackrosezy** [gogs/gogs#403]
Currently content jumps when a scrollbar appears. A little css will keep navigation between pages feel smooth.

``` css
body { overflow-y: scroll }
```

http://stackoverflow.com/questions/12582555/always-show-browser-scrollbar-to-prevent-page-jumping
