### ISSUE TITLE
Docker: push error: xorm.log permission change to root:root by daily log rotation

### ISSUE THREAD

**Issue by CodeSmolder** [gogs/gogs#5294]
- Gogs version (or commit ref): docker gogs/gogs:0.11.53 (latest)
- Git version: 2.11.3
- Operating system: alpine:3.5
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
2018/06/13 16:08:52 [TRACE] Session ID: 0147aeb0d35b49d0
2018/06/13 16:08:52 [TRACE] CSRF Token: rYcoziB06M2v2y6YNTFVO7G8qZ46MTUyODgzMzg3NDc0NjQ3OTMxOQ==
2018/06/13 16:08:52 [TRACE] Template: user/dashboard/dashboard
2018/06/13 16:09:04 [TRACE] Session ID: 0147aeb0d35b49d0
2018/06/13 16:09:04 [TRACE] CSRF Token: rYcoziB06M2v2y6YNTFVO7G8qZ46MTUyODgzMzg3NDc0NjQ3OTMxOQ==
2018/06/13 16:09:04 [TRACE] Template: repo/create
2018/06/13 16:09:09 [TRACE] Session ID: 0147aeb0d35b49d0
2018/06/13 16:09:09 [TRACE] CSRF Token: rYcoziB06M2v2y6YNTFVO7G8qZ46MTUyODgzMzg3NDc0NjQ3OTMxOQ==
2018/06/13 16:09:09 [TRACE] Repository created [7]: ap-test/ap-test2
2018/06/13 16:09:09 [TRACE] Session ID: 0147aeb0d35b49d0
2018/06/13 16:09:09 [TRACE] CSRF Token: rYcoziB06M2v2y6YNTFVO7G8qZ46MTUyODgzMzg3NDc0NjQ3OTMxOQ==
2018/06/13 16:09:09 [TRACE] Template: repo/bare
2018/06/13 16:10:08 [TRACE] Session ID: 5eb4ba1112f81ea7
2018/06/13 16:10:08 [TRACE] CSRF Token: fXPcbD8npdZY2qDgTVCRl_fq2_86MTUyODkwNjIwODkzODUzNTc2Mg==
2018/06/13 16:10:23 [TRACE] Session ID: e03863b9a8c9b363
2018/06/13 16:10:23 [TRACE] CSRF Token: fbMQE6L0SqnE7YuSYuHqSQbFCt46MTUyODkwNjIyMzkzNzk3MTgxMA==
2018/06/13 16:10:23 [TRACE] HTTPGit - Authenticated user: ap-test
2018/06/13 16:10:24 [TRACE] Session ID: de779186c056d069
2018/06/13 16:10:24 [TRACE] CSRF Token: EaRyW_llrfettOal5VZPzDyAL8o6MTUyODkwNjIyNDAzMjEyNzIyMw==
2018/06/13 16:10:24 [TRACE] HTTPGit - Authenticated user: ap-test

## Description
When pushing to master in a newly created repository the following error occurs. This is caused by a file system permission change on log file xorm.log (from git:git to root:root) when the daily log rotation takes place. When I change back the permission manually to git:git everything works as expected.

This is what the shell looks like in case of the error:

root@60b7ed2d5c57# touch README.md
root@60b7ed2d5c57# git init
Initialized empty Git repository in /root/ap-test2/.git/
root@60b7ed2d5c57# git add README.md
root@60b7ed2d5c57# git commit -m "first commit"
[master (root-commit) 0f0554f] first commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 README.md
root@60b7ed2d5c57# git remote add origin https://gogs.test.de/ap-test/ap-test2.git
root@60b7ed2d5c57# git push -u origin master
Username for 'https://gogs.test.de': ap-test
Password for 'https://ap-test@gogs.test.de': 
Counting objects: 3, done.
Writing objects: 100% (3/3), 194 bytes | 97.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0)
remote: Gogs: Internal error
To https://gogs.test.de/ap-test/ap-test2.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://gogs.test.de/ap-test/ap-test2.git'

These are the permissions after daily log rotations:
-rw-r-----    1 git      git           6599 Jun 13 16:42 gogs.log
-rw-r-----    1 git      git          75604 Jun 10 00:02 gogs.log.2018-06-09
-rw-r-----    1 git      git           7502 Jun 11 00:02 gogs.log.2018-06-10
-rw-r-----    1 git      git          47022 Jun 12 00:02 gogs.log.2018-06-11
-rw-r-----    1 git      git          20199 Jun 13 00:02 gogs.log.2018-06-12
drwxr-xr-x    2 git      git           4096 Jun 13 16:10 hooks
-rw-r-----    1 root     root             0 Jun 13 00:35 xorm.log
-rw-r-----    1 git      git          22256 Jun  9 14:32 xorm.log.2018-06-09
-rw-r-----    1 git      git              0 Jun 10 00:35 xorm.log.2018-06-10
-rw-r-----    1 git      git              0 Jun 11 00:35 xorm.log.2018-06-11
-rw-r-----    1 git      git              0 Jun 12 00:35 xorm.log.2018-06-12

**Comment by Unknwon** [comment]
Hi, does the "log" directory only exists inside Docker container or you have volumed to your local file system? Also, what is the command you used to start the gogs/gogs container?

**Comment by CodeSmolder** [comment]
Hi, in my configuration the "log" directory only exists inside Docker.

I use docker-compose for starting the containers with this command: `docker-compose -f docker-compose.yml up -d`

This is the configuration of my docker-compose.yml file: 
```
version: '3.2'
services:
  git-gogs:
    image: gogs/gogs:0.11.53
    container_name: git-gogs
    ports:
      - "2223:22"
      - "3000:3000"
    volumes:
      - type: bind
        source: "/docker-mnt/git-gogs/git-gogs"
        target: "/data"
      - type: bind
        source: "/docker-mnt/git-gogs/git-gogs-custom/robots.txt"
        target: "/app/gogs/public/robots.txt"
      - type: bind
        source: "/docker-mnt/git-gogs/backup"
        target: "/mnt"
    environment:
      - USER=git
    links:
      - git-mysql
  git-mysql:
    image: mysql:5.7.22
    ports:
      - 3312:3306
    container_name: git-mysql
    volumes:
      - type: bind
        source: "/docker-mnt/git-gogs/mysql"
        target: "/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: [MySQLRootPassword]
  git-adminer:
    image: adminer
    ports:
      - 9007:8080
    container_name: git-adminer
    links:
      - git-mysql
```
