### ISSUE TITLE
In Admin panel the code block is out of the main block

### ISSUE THREAD

**Issue by UnicornCodes** [gogs/gogs#5453]
- Gogs version (or commit ref): master
- Git version: 2.17.1
- Operating system: Ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

In Admin panel the code block is out of the main block

![screenshot](https://user-images.githubusercontent.com/43472149/46516041-20206680-c885-11e8-873d-91911dde4a6f.png)

**Comment by GramThanos** [comment]
I don't think this is exactly a bug.

Quick fix would be to add a `word-break` on it's CSS rule:
```css
.admin dl.admin-dl-horizontal dd {
    margin-left: 240px;
    word-break: break-all;
}
```

 Or parse the configuration (maybe replace `,` with a `<br>` new line)
