### ISSUE TITLE
Gogs installation (using PostgreSQL) fails with 'Admin account setting is invalid: name is reserved [name: admin]''

### ISSUE THREAD

**Issue by mmoser18** [gogs/gogs#5672]
Hi - I wanted to use the docker image of Gogs as my repo for a local CI environment.

So I pulled and started the docker image gogs/gogs. 
After startup I opened it's admin page (http://192.168.1.15:3000/install in my case).
Came to the conclusion that I first need to install a DB and chose PostgreSQL  --> I installed the plain vanilla postgres docker image which gets started via docker-compose using:
```
  gogs-db:
    image: postgres
    hostname: gogs-db
    ports:
      - "18432:5432"
    environment:
      POSTGRES_PASSWORD: 'postgres-admin-pwd-here'
    restart: unless-stopped
    volumes:
      - gogs-db-data:/var/lib/postgresql/data
    networks:
      - facto
```

and created a user and DB, both called 'gogs', i.e.:
```
ash-4.3# docker exec -it ci_gogs-db_1 psql -U postgres
postgres=# CREATE USER gogs WITH PASSWORD 'gogs-pwd-here';
CREATE ROLE
postgres=# CREATE DATABASE gogs OWNER gogs;
CREATE DATABASE
postgres=# \q
```

Then I continued with the gogs install:
```
Database Type: PostgreSQL
Host: 192.168.1.15:18432
User: gogs
Pwd: gogs-pwd-here
…
```

Install starts but then aborts with the error message:
Admin account setting is invalid: name is reserved [name: admin]

Nowhere on the "Install Steps For First-time Run" form do I mention 'admin', so where does this come from? Does that mean, that Postgres is not usable as DB for Gogs? Or how can I prevent this error?
