### ISSUE TITLE
All configurations fail as `custom` path run in docker, e.g. `custom/conf/app.ini`

### ISSUE THREAD

**Issue by sinlov** [gogs/gogs#5994]
**Describe the bug**

All configurations fail, whatever in right path `custom`, when run in docker

**Gogs version or commit**

```
bash-5.0# ./gogs --version
Gogs version 0.12.0+dev
```

**Git version**

```
$ git version
git version 2.22.2
```

**Operating system**

```
Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Database**

SQLite

**To Reproduce**
1. docker-compose.yml

```yml
version: '3.7'
networks:
  default:
services:
  gogs:
    container_name: "gogs"
    image: gogs/gogs:latest
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data/gogs/data:/data
    ports:
      - "40080:3000"
      - "40022:22"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
```

- gogs/gogs               latest               f5089a318904
- gogs/gogs               0.11.91              ece384423e6f

`both image can not load custom config`

in contain, show custom config

```bash
bash-5.0# echo $GOGS_CUSTOM
/data/gogs
bash-5.0# cat $GOGS_CUSTOM/custom/conf/app.ini
APP_NAME = testGogs

[service]
REGISTER_EMAIL_CONFIRM = false
ENABLE_NOTIFY_MAIL     = false
DISABLE_REGISTRATION   = true
ENABLE_CAPTCHA         = false
REQUIRE_SIGNIN_VIEW    = true

[auth]
; Whether to disallow anonymous users visiting the site.
REQUIRE_SIGNIN_VIEW = true
; Whether to disable self-registration. When disabled, accounts would have to be created by admins.
DISABLE_REGISTRATION = true
; Whether to enable captcha validation for registration
ENABLE_REGISTRATION_CAPTCHA = true
```

**Can you reproduce the bug at https://try.gogs.io?**

no

**Expected behavior**

Let custom config can use! 
I need inject custom head and footer!
