### ISSUE TITLE
Docker + traefik - unable to install with path prefix

### ISSUE THREAD

**Issue by pmall** [gogs/gogs#6198]
Hi,

Im using docker compose + traefik reverse proxy to install gogs with a path prefix. Here's my docker compose:

```
version: '3'
services:
    front:
        image: gogs/gogs:latest
        ports:
            - '922:22'
        volumes:
            - ./data:/data/gogs
        networks:
            - default
            - proxy
        labels:
            - traefik.http.routers.gogs.rule=Host(`${APP_HOST}`) && PathPrefix(`/gogs`)
            - traefik.http.services.gogs.loadbalancer.server.port=3000
        depends_on:
            - database
    database:
        image: postgres:12
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_DB=gogs
networks:
    proxy:
        external: true
```

However, when going to `http://myapphost/gogs` I'm redirected to `http://myapphost/install` which of course is not the intended behavior.

I cant figure out a way to specify the `ROOT_URL` *before* installing.
