### ISSUE TITLE
Repository page timestamps not updated on new commits, wrong sorting

### ISSUE THREAD

**Issue by cthu1hoo** [gogs/gogs#6459]
After pushing new commits timestamps in repository view are not updated and it's not sorted properly, i.e. last updated projects don't go on top:

![image](https://user-images.githubusercontent.com/47687909/103121567-cb4baf00-468d-11eb-8185-7938c76b16e9.png)

And yet:

![image](https://user-images.githubusercontent.com/47687909/103121558-c0911a00-468d-11eb-90b7-d21276fc9607.png)

Application version: 0.13.0+dev
Git version: 2.24.3
Go version: go1.14.7
Build time: 2020-12-13 02:27:53 UTC
Build commit: af6510fd17c5cf3d31518dc412bc173e04ec25a1 

I'm using latest image from docker with postgresql (11-alpine):

```
version: '3'

services:
  db:
    image: postgres:11-alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - db.env

  app:
    image: gogs/gogs:latest
    restart: always
    ports:
      - 127.0.0.1:10022:22
      - 127.0.0.1:10080:3000
    volumes:
      - data:/data
      - ./passwd:/etc/passwd
      - /home/git/.ssh:/data/git/.ssh
    env_file:
      - db.env
    depends_on:
      - db

volumes:
  db:
  data:
```

This worked fine using Gogs docker image tagged 0.12. Nothing in gogs.log but a few complains in xorm.log, nothing mentioning timestamps though.
