### ISSUE TITLE
docker container restart - site no longer available, requires reinstall/initialization

### ISSUE THREAD

**Issue by tonydm** [gogs/gogs#6618]
**Describe the bug**
After installation and initialization of db connection and base settings and set up of first repo, all is well.  I execute a docker-compose down && docker-compose up -d and site no longer accessible.

**Gogs version and commit**
docker image tag: gogs/gogs:latest

**Git version**
container image runtime:
```
da@docker2:[10.0.2.224]~/DockerServices/gitserver$ docker exec -it gitserver_gogs_1 /bin/bash -c "git --version"
git version 2.24.4
```

**Operating system**
```
da@docker2:[10.0.2.224]~/DockerServices/gitserver$ cat /etc/issue
Ubuntu 20.04.1 LTS \n \l
```

**Database**
docker image: postgres:9.5

**To Reproduce**
1. docker-compose up -d
2. Site comes up.  Complete initial db, base settings and create admin user via web interface
3. Site comes up.  Clicking through user settings, etc works
4. Create initial repository, success
5. docker-compose down && docker-compose up -d
6. Site no longer accessible

**Can you reproduce the bug at https://try.gogs.io?**
Not applicable

**Expected behavior**
Restart of container results in site being available

**Actual behavior**
After container restart, site no longer reachable.
browser page:

This site can’t be reached
10.0.2.224 refused to connect.

**Additional context**
**docker-compose logs**
```
da@docker2:[10.0.2.224]~/DockerServices/gitserver$ docker-compose logs -f --tail=1000
Attaching to gitserver_gogs_1, gitserver_postgres_1
postgres_1  | 
postgres_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1  | 
postgres_1  | LOG:  database system was shut down at 2021-09-15 06:58:07 MST
postgres_1  | LOG:  MultiXact member wraparound protections are now enabled
postgres_1  | LOG:  autovacuum launcher started
postgres_1  | LOG:  database system is ready to accept connections
gogs_1      | usermod: no changes
gogs_1      | init:crond  | Cron Daemon (crond) will be run as requested by s6
gogs_1      | Backup disabled: BACKUP_INTERVAL has not been found
gogs_1      | Sep 15 06:58:54 syslogd started: BusyBox v1.31.1
gogs_1      | Sep 15 13:58:54 sshd[40]: Server listening on :: port 22.
gogs_1      | Sep 15 13:58:54 sshd[40]: Server listening on 0.0.0.0 port 22.
gogs_1      | 2021/09/15 06:58:54 [TRACE] Log mode: File (Info)
gogs_1      | Sep 15 14:00:00 crond[38]: USER root pid  81 cmd run-parts /etc/periodic/15min
gogs_1      | Sep 15 14:00:00 crond[38]: USER root pid  82 cmd run-parts /etc/periodic/hourly
```

**docker-compose.yml**
```
version: '2'
services:
    postgres:
      image: postgres:9.5
      restart: always
      environment:
        - "POSTGRES_USER=gogs"
        - "POSTGRES_PASSWORD=gogs"
        - "POSTGRES_DB=gogs"
      volumes:
        - ./postgres_db:/var/lib/postgresql/data
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
      networks:
        - gogs

    gogs:
      image: gogs/gogs:latest
      restart: always
      ports:
        - "2222:22"
        - "3999:3000"
      links:
        - postgres
      environment:
        - "RUN_CROND=true"
      networks:
        - gogs
      volumes:
        - nfsmount_GITREPO:/data
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
      depends_on:
        - postgres

networks:
  gogs:
    driver: bridge

volumes:
  # Mount NFS Share from NAS1
  nfsmount_GITREPO:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.2.246
      device: ":/mnt/BigPool/GITREPO"

```
