### ISSUE TITLE
Wehook  not trigger

### ISSUE THREAD

**Issue by xsean2020** [gogs/gogs#7065]
### Gogs version

0.12.*

### Git version

- Server: 
- Client: 

### Operating system

centos docker.   gogs:0.12.*

### Database

mysql

### Describe the bug

web test webhook work fine  , but pushed wehook not trigger 

### To reproduce

![image](https://user-images.githubusercontent.com/62974981/174207251-51d3d970-fdc9-4eee-8556-e650b2113ab7.png)

### Expected behavior

when push code ,auto trigger webhook

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsean2020** [comment]
start with fllow :
docker-compose.yaml
```
version: '2.3'
networks:
 gogsnetwork:
   ipam:
     driver: default

services:
    mysql:
      image: mysql:5.7
      restart: always
      networks:
         gogsnetwork:
      environment:
        - MYSQL_ROOT_PASSWORD=test124
        - MYSQL_DATABASE=gogs
      volumes:
        - /gogos/mysql:/var/lib/mysql

    gogs:
      image: gogs/gogs:0.12.5
      restart: always
      networks:
         gogsnetwork:
      ports:
        - "30042:22"
        - "30043:3000"
      volumes:
        - /gogos/data:/data
      links:
        - mysql
      depends_on:
        - mysql
```
