### ISSUE TITLE
make div "editor-toolbar" sticky when scrolling and reached the top of the site

### ISSUE THREAD

**Issue by ecxod** [gogs/gogs#7136]
### Describe the feature

When I use the editor and scroll up, the "editor-toolbar" disappears from the page, so every time I want to press a button there, I have to scroll back down. This is relatively annoying when you are in a hurry.
it would be pretty handy if the toolbar would stay sticky at the top of the page

### Describe the solution you'd like

add this to your gogs.css

```css
.editor-toolbar{
    position: sticky;
    top: 0;
    background-color:#fff;
    border: #ccc 1px solid;
}
```

### Describe alternatives you've considered

I can suppy a PR  but I thought its more simple if you add the lines

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
