### ISSUE TITLE
with drone in a docker compose, on restart, after first drone login, I need to delete gogs Personal Access Tokens in order to login again

### ISSUE THREAD

**Issue by magowiz** [gogs/gogs#7172]
### Gogs version

0.13.0+dev

### Git version

- Server: 2.32.3
- Client: 2.34.1

### Operating system

Ubuntu 22.04

### Database

SQLite 3

### Describe the bug

I can, from drone, register to gogs, a Personal Account Token is created, I'm able to run pipelines and so on, after I restart the infrastructure, if from drone I try to login I get "Unauthorized", in order to login again I have to delete Personal Access Token from gogs and perform a new registration.

mine docker-compose.yml:
`version: "3"
services:
  gogs:
    container_name: 'gogs'
    image: gogs/gogs
    ports:
      - "3000:3000"
      - "8022:22"
      - '8443:443'
    volumes:
      - ./gogs:/data
    networks:
      - cicd

  drone-server:
    container_name: 'drone-server'
    image: drone/drone
    ports:
      - "8080:80"
      - "8843:443"
    volumes:
      - ./drone:/var/lib/drone/
    depends_on:
      - gogs
    environment:
      - DRONE_GOGS_SERVER=http://gogs:3000
      - DRONE_RPC_SECRET=XXXXXXX
      - DRONE_SERVER_HOST=drone-server
      - DRONE_SERVER_PROTO=http
      - DRONE_GOGS_URL=http://gogs:3000
      - DRONE_GOGS=true
        #- DRONE_LOGS_DEBUG=true
    networks:
      - cicd

  drone-agent:
    container_name: 'drone-agent'
    image: drone/drone-runner-docker:1
    command: agent
    depends_on: [drone-server]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_SECRET=XXXXXXX
      - DRONE_RUNNER_NAME=facchino
      - DRONE_GOGS_URL=http://gogs:3000/
      - DRONE_DOCKER_NETWORK_ID=cicd
      - DRONE_RUNNER_NETWORKS=cicd
    networks:
      - cicd

networks:
  cicd:
    name: cicd
`

### To reproduce

1. launch above docker compose with `docker compose up`
2. configure gogs, setup a repository
3. login via drone.io into gogs
4. do things like commit and push, to trigger drone
5. it works
6. stop the compose
7. start the compose
8. go with browser into drone page and try to login ("Unauthorized")

### Expected behavior

on second run (restart) I should be able to login inside gogs via drone

### Additional context

[gogs.log](https://github.com/gogs/gogs/files/9726921/gogs.log)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vaecebyZ** [comment]
I'm also getting this error and it hasn't been fixed until now. XD

**Comment by robert-m-johnson** [comment]
I'm also getting the same issue.

* OS: Pop OS 22.04
* Database: SQLite3

`docker-compose.yaml`:
```yaml
version: '3'

services:
  gogs:
    image: gogs/gogs:0.13.0
    volumes:
      - ./gogs:/data
    ports:
      - "3002:3000"

  drone-server:
    image: drone/drone:2.16.0
    ports:
      - "8000:80"
    restart: always
    environment:
      - DRONE_AGENTS_ENABLED=true
      - DRONE_GOGS_SERVER=http://gogs:3000
      - DRONE_RPC_SECRET=mysecret
      - DRONE_SERVER_HOST=drone-server
      - DRONE_SERVER_PROTO=http
      - DRONE_GOGS_SKIP_VERIFY=false

  drone-runner:
    image: drone/drone-runner-docker:1.8.3
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_SECRET=mysecret
      - DRONE_RUNNER_CAPACITY=1
      - DRONE_RUNNER_NAME=my-first-runner
```
